### ISSUE TITLE
Many thumbnails are pixelated

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduWebsite2015#1] opened 2015-05-26 23:31 UTC
See for example, the image here: http://wikiedu.org/blog/2015/04/10/arizona-geoclub-wikipedia/

See also the About Us profiles: http://wikiedu.org/about-us/

**Comment by dmak78** [comment] 2015-05-27 16:38
@ragesoss This should be fixed now. Needed to up the resolution settings on the Team Manager thumbnails. The images in the post were being stretch to 100% of the post container, to fix this I just set MAX width instead, so they should display as intended now.

**Closed as completed by dmak78** 2015-05-27 16:38 UTC
Labels: bug

**Comment by ragesoss** [comment] 2015-05-27 16:42
Nice. Thanks @dmak78 !
